name: list_data
description: "A new Flutter plugin project."
version: 0.0.1
homepage: "list_data"
publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: any
  error_handling:
    git:
      url: https://github.com/Renoldi/error_handling
      ref: master

  flutter_widget_from_html: any
  font_awesome_flutter: any
  skeleton_text: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
